<template>
  <div><div class="page-head"><div><h1 class="page-title">你好，{{ user?.name || user?.username || '同学' }} 👋</h1><p class="page-subtitle">今天也为自己留一段专注的练习时间吧。</p></div><el-button type="primary" @click="router.push('/rooms')">预约琴房</el-button></div>
    <el-row :gutter="20"><el-col :xs="24" :md="16"><el-card class="soft-card banner-card" shadow="never"><el-carousel v-if="banners.length" height="260px"><el-carousel-item v-for="item in banners" :key="item.id"><a :href="item.link || '#/rooms'" class="banner-link"><img :src="item.image" alt="琴房活动" /><span v-if="item.image?.includes('banner-default')">舒心练琴，从预约开始</span></a></el-carousel-item></el-carousel><el-empty v-else description="暂无轮播内容" /></el-card></el-col><el-col :xs="24" :md="8"><el-card class="soft-card quick-card" shadow="never"><template #header><div class="card-title">快捷入口</div></template><div class="quick-grid"><el-button v-for="item in quickLinks" :key="item.path" text @click="router.push(item.path)"><span class="quick-icon">{{ item.icon }}</span>{{ item.label }}</el-button></div></el-card><el-card class="soft-card tip-card" shadow="never"><div class="tip-label">预约小贴士</div><p>提前查看空闲时段，退约后关注者会收到站内提醒。</p></el-card></el-col></el-row>
    <el-card class="soft-card notice-card" shadow="never"><template #header><div class="card-title">系统公告</div></template><el-collapse v-if="notices.length"><el-collapse-item v-for="notice in notices" :key="notice.id" :title="notice.title" :name="notice.id"><p class="notice-content">{{ notice.content }}</p><small>{{ notice.createdAt || '' }}</small></el-collapse-item></el-collapse><el-empty v-else description="暂无公告" /></el-card>
  </div>
</template>
<script setup>
import { onMounted, ref } from 'vue'; import { useRouter } from 'vue-router'; import { getBanners, getNotices } from '../api/content'; import { ElMessage } from 'element-plus'
const router = useRouter(); const user = ref(JSON.parse(localStorage.getItem('user') || 'null')); const banners = ref([]); const notices = ref([])
const quickLinks = [{ label: '我的预约', path: '/bookings', icon: '▣' }, { label: '我的关注', path: '/watches', icon: '♡' }, { label: '消息中心', path: '/messages', icon: '✉' }, { label: '意见反馈', path: '/feedback', icon: '☷' }]
onMounted(async () => { try { [banners.value, notices.value] = await Promise.all([getBanners(), getNotices()]) } catch (e) { ElMessage.warning(e.message) } })
</script>
<style scoped>
.banner-card{overflow:hidden}.banner-link{display:block;position:relative;height:260px;background:#e4f3f1}.banner-link img{width:100%;height:100%;object-fit:cover}.banner-link span{position:absolute;left:30px;bottom:24px;color:#fff;font-size:24px;font-weight:700;text-shadow:0 2px 8px #1238}.quick-card{height:260px}.card-title{font-size:17px;font-weight:700}.quick-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.quick-grid .el-button{height:78px;display:flex;flex-direction:column;gap:6px;color:#39544f}.quick-icon{font-size:24px;color:#168f83}.tip-card{margin-top:20px;background:linear-gradient(135deg,#f0faf8,#f3f7ff)}.tip-label{color:#168f83;font-weight:700}.tip-card p{margin:8px 0 0;color:#667b81;font-size:13px;line-height:1.7}.notice-card{margin-top:20px}.notice-content{line-height:1.8;margin:0 0 6px;color:#53676d}
</style>
