<template><div><div class="page-head"><div><h1 class="page-title">消息中心</h1><p class="page-subtitle">空出提醒和系统消息都会显示在这里。</p></div><div style="display:flex;gap:8px"><el-button @click="load">刷新</el-button><el-button type="primary" plain @click="readAll">全部已读</el-button></div></div><el-card class="soft-card" shadow="never"><el-segmented v-model="unread" :options="[{label:'全部消息',value:false},{label:'仅未读',value:true}]" @change="load"/><div v-if="items.length" class="message-list"><div v-for="item in items" :key="item.id" class="message-item" :class="{unread:!item.isRead}"><div class="message-icon">{{ item.msgType==='vacancy'?'♬':'✉' }}</div><div class="message-body"><div class="message-title">{{ item.msgType==='vacancy'?'空出提醒':'系统消息' }}<el-tag v-if="!item.isRead" size="small" type="danger">未读</el-tag></div><p>{{ item.content }}</p><small>{{ item.createdAt || '' }}</small></div><el-button v-if="!item.isRead" link type="primary" @click="read(item)">标记已读</el-button></div></div><el-empty v-else-if="!loading" description="暂无消息"/><div class="pager"><el-pagination v-if="total" v-model:current-page="page" layout="total, prev, pager, next" :total="total" :page-size="10" @current-change="load"/></div></el-card></div></template>
<script setup>
import { onMounted, ref } from 'vue'; import { ElMessage } from 'element-plus'; import { listMessages, readAllMessages, readMessage } from '../api/messages'
import { refreshUnread } from '../utils/unread'
const unread=ref(false);const items=ref([]);const total=ref(0);const page=ref(1);const loading=ref(false);async function load(){loading.value=true;try{const d=await listMessages({unread:unread.value?1:undefined,page:page.value,size:10});items.value=d?.list||[];total.value=d?.total||0}catch(e){ElMessage.error(e.message)}finally{loading.value=false}}async function read(item){try{await readMessage(item.id);item.isRead=true;ElMessage.success('已标记为已读');refreshUnread()}catch(e){ElMessage.error(e.message)}}
async function readAll(){try{await readAllMessages();ElMessage.success('已全部标记为已读');await load();refreshUnread()}catch(e){ElMessage.error(e.message)}}onMounted(load)
</script>
<style scoped>.message-list{margin-top:22px}.message-item{display:flex;align-items:flex-start;gap:14px;padding:18px 4px;border-bottom:1px solid #edf2f2}.message-item.unread{background:#f8fcfb}.message-icon{display:grid;place-items:center;width:40px;height:40px;background:#e4f5f2;color:#168f83;border-radius:12px;font-size:20px}.message-body{flex:1}.message-title{display:flex;align-items:center;gap:8px;font-weight:700}.message-body p{margin:8px 0;color:#5e7077;line-height:1.7}.message-body small{color:#98a6aa}.pager{display:flex;justify-content:center;padding-top:20px}@media(max-width:560px){.message-item .el-button{padding:0}}
</style>
