<template><div><div class="page-head"><div><h1 class="page-title">个人中心</h1><p class="page-subtitle">管理你的资料、会员与信用状态。</p></div></div><el-row :gutter="20"><el-col :xs="24" :md="10"><el-card class="soft-card profile-card" shadow="never"><el-avatar :size="72" class="avatar">{{ (user?.name || user?.username || '用').slice(0,1) }}</el-avatar><h2>{{ user?.name || user?.username }}</h2><p class="muted">{{ user?.username }}</p><el-descriptions :column="1" border><el-descriptions-item label="学号">{{ user?.studentNo || '—' }}</el-descriptions-item><el-descriptions-item label="邮箱">{{ user?.email || '—' }}</el-descriptions-item><el-descriptions-item label="会员"><el-tag :type="user?.isMember?'success':'info'">{{ user?.isMember?'会员':'普通用户' }}</el-tag></el-descriptions-item><el-descriptions-item label="信用分"><span :class="{'low-credit':(user?.credit||0)<60}">{{ user?.credit ?? '—' }}</span></el-descriptions-item></el-descriptions></el-card></el-col><el-col :xs="24" :md="14"><el-card class="soft-card" shadow="never"><template #header><b>修改密码</b></template><el-form ref="formRef" :model="form" :rules="rules" label-position="top"><el-form-item label="旧密码" prop="password"><el-input v-model="form.password" type="password" show-password /></el-form-item><el-form-item label="新密码" prop="newPassword"><el-input v-model="form.newPassword" type="password" show-password /></el-form-item><el-form-item label="确认新密码" prop="confirm"><el-input v-model="form.confirm" type="password" show-password /></el-form-item><el-button type="primary" :loading="saving" @click="save">保存新密码</el-button></el-form></el-card></el-col></el-row></div></template>
<script setup>
import { onMounted, reactive, ref } from 'vue'; import { ElMessage } from 'element-plus'; import { changePassword, profile } from '../api/auth'
const user=ref(JSON.parse(localStorage.getItem('user')||'null'));const formRef=ref();const saving=ref(false);const form=reactive({password:'',newPassword:'',confirm:''});const rules={password:{required:true,message:'请输入旧密码',trigger:'blur'},newPassword:[{required:true,message:'请输入新密码',trigger:'blur'},{pattern:/^(?=.*[A-Za-z])(?=.*\d)\S{8,20}$/,message:'新密码为 8 至 20 位且至少含字母与数字',trigger:'blur'}],confirm:{validator:(_,v,cb)=>v!==form.newPassword?cb(new Error('两次输入的密码不一致')):cb(),trigger:'blur'}}
// 后端校验以后端为准，命中字段错误时直接标在对应输入框下方
function showFieldError(form, e) { const field = e?.data?.field; const item = field && form.value?.fields?.find((f) => f.prop === field); if (item) { item.validateState = 'error'; item.validateMessage = e.message } else { ElMessage.error(e.message) } }
onMounted(async()=>{try{const data=await profile();user.value=data;localStorage.setItem('user',JSON.stringify(data))}catch{}});async function save(){if(!(await formRef.value?.validate().catch(()=>false)))return;saving.value=true;try{await changePassword({password:form.password,newPassword:form.newPassword});ElMessage.success('密码修改成功，请重新登录');localStorage.removeItem('token');localStorage.removeItem('user');window.location.hash='#/login'}catch(e){showFieldError(formRef,e)}finally{saving.value=false}}
</script>
<style scoped>.profile-card{text-align:center}.avatar{background:#168f83;font-size:28px}.profile-card h2{margin:14px 0 4px}.muted{color:#87969b;margin:0 0 20px}.low-credit{color:#e66b50;font-weight:700}</style>
