<template>
  <div><div class="page-head"><div><h1 class="page-title">琴房浏览</h1><p class="page-subtitle">选择适合你的空间，查看实时空闲时段。</p></div></div><el-card class="soft-card filter-card" shadow="never"><el-form inline @submit.prevent="search"><el-form-item label="搜索"><el-input v-model="filters.q" clearable placeholder="琴房名称" @keyup.enter="search" /></el-form-item><el-form-item label="类型"><el-select v-model="filters.type" clearable placeholder="全部"><el-option label="对外琴房" value="outer" /><el-option label="对内琴房" value="inner" /></el-select></el-form-item><el-button type="primary" @click="search">查询</el-button><el-button @click="reset">重置</el-button></el-form></el-card><el-alert v-if="error" :title="error" type="warning" show-icon closable class="alert" /><el-row v-if="rooms.length" :gutter="20"><el-col v-for="room in rooms" :key="room.id" :xs="24" :sm="12" :lg="8" class="room-col"><el-card class="soft-card room-card" shadow="never"><div class="room-top"><el-tag :type="room.roomType === 'inner' ? 'warning' : 'success'">{{ room.roomType === 'inner' ? '对内' : '对外' }}</el-tag><span class="room-id">#{{ room.id }}</span></div><h2>{{ room.name }}</h2><p>{{ room.description || '暂无琴房说明' }}</p><div class="room-time">开放时间：{{ minuteToTime(room.openStart) }} - {{ minuteToTime(room.openEnd) }}</div><el-button type="primary" plain class="detail-btn" @click="router.push(`/rooms/${room.id}`)">查看详情</el-button></el-card></el-col></el-row><el-empty v-else-if="!loading" description="没有找到符合条件的琴房" /><div v-if="total" class="pager"><el-pagination v-model:current-page="filters.page" v-model:page-size="filters.size" layout="total, prev, pager, next" :total="total" @current-change="load" /></div><div v-if="loading" class="loading"><span class="spinner">⟳</span> 加载中…</div></div>
</template>
<script setup>
import { onMounted, reactive, ref } from 'vue'; import { useRouter } from 'vue-router'; import { listRooms } from '../api/rooms'; import { minuteToTime } from '../utils/time'
const router = useRouter(); const rooms = ref([]); const total = ref(0); const loading = ref(false); const error = ref(''); const filters = reactive({ q: '', type: '', page: 1, size: 9 })
async function load(){ loading.value=true; error.value=''; try { const data=await listRooms(filters); rooms.value=data?.list || []; total.value=data?.total || 0 } catch(e){ error.value=e.message } finally{ loading.value=false } }
function search(){ filters.page=1; load() }; function reset(){ filters.q=''; filters.type=''; search() }; onMounted(load)
</script>
<style scoped>.filter-card{margin-bottom:20px}.alert{margin-bottom:20px}.room-col{margin-bottom:20px}.room-card{height:100%;min-height:260px}.room-top{display:flex;justify-content:space-between}.room-id{color:#9aa9ad;font-size:13px}.room-card h2{font-size:20px;margin:18px 0 10px}.room-card p{height:48px;color:#71808c;line-height:1.6;margin:0 0 16px;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.room-time{padding:11px;background:#f2f8f7;color:#42706a;font-size:13px;border-radius:8px}.detail-btn{width:100%;margin-top:18px}.pager{text-align:center;margin:10px 0 25px}.loading{text-align:center;color:#168f83;padding:30px}</style>
